#!/usr/bin/env bash
set -eu
cd "${0%/*}" || exit 1
# shellcheck disable=SC1091
. ../../marine_env.sh
# Source Foundation 13 clean functions
. "$WM_PROJECT_DIR/bin/tools/CleanFunctions"

# Remove surfaces
rm -f constant/geometry/propeller*.obj.gz

cleanCase
cleanExplicitFeatures

#------------------------------------------------------------------------------
