#!/bin/sh
set -eu
cd "${0%/*}" || exit 1
# shellcheck disable=SC1091
. ../../marine_env.sh
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"
marine_require_command marineFoam

if [ ! -d constant/polyMesh ]; then
    ./Allmesh.FoamPilot
fi
runApplication marineFoam -solver incompressibleVoF
runApplication postProcess -func forces

#------------------------------------------------------------------------------
