#!/usr/bin/env python3
"""Generate OpenFOAM maps through FoamPilot's direct PyVista reader."""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "foampilot" / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from foampilot.postprocess.openfoam_direct import OpenFOAMDirectReader


def finite_stats(values: np.ndarray) -> dict[str, float | int]:
    arr = np.asarray(values, dtype=float).reshape(-1)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return {"count": 0}
    return {
        "count": int(arr.size),
        "min": float(np.min(arr)),
        "max": float(np.max(arr)),
        "mean": float(np.mean(arr)),
        "p05": float(np.percentile(arr, 5)),
        "p50": float(np.percentile(arr, 50)),
        "p95": float(np.percentile(arr, 95)),
    }


def render_field(mesh, field: str, output: Path, title: str, cmap: str) -> None:
    import pyvista as pv

    pl = pv.Plotter(off_screen=True, window_size=(1500, 950))
    pl.set_background("white")
    pl.add_mesh(
        mesh,
        scalars=field,
        cmap=cmap,
        show_edges=False,
        scalar_bar_args={"title": title, "vertical": True},
    )
    pl.add_axes(line_width=2)
    pl.view_isometric()
    pl.camera.zoom(1.15)
    pl.screenshot(str(output))
    pl.close()


def surface_cell_values(volume_mesh, surface, values: np.ndarray) -> np.ndarray:
    """Map volume-cell values to all triangles generated by extract_surface."""
    ids = surface.cell_data.get("vtkOriginalCellIds")
    if ids is None:
        ids = surface.cell_data.get("vtkOriginalCellIds0")
    if ids is None:
        # Fallback for VTK versions that do not preserve original ids:
        # repeat each source cell value according to generated surface cells.
        n_surface = surface.n_cells
        if n_surface == len(values):
            return np.asarray(values)
        raise RuntimeError("PyVista did not preserve vtkOriginalCellIds during surface extraction")
    return np.asarray(values)[np.asarray(ids, dtype=int)]


def render_patch(reader, patch: str, field: str, time: str, output: Path, title: str, cmap: str) -> dict:
    import pyvista as pv

    patch_cells = reader.get_patch_cells(patch)
    surface = reader.mesh.extract_cells(patch_cells).extract_surface().copy()
    values = reader.read_field(field, time_step=time)
    if len(values) == reader.mesh.n_cells:
        surface_values = surface_cell_values(reader.mesh, surface, values)
        surface.cell_data[field] = surface_values
        arr = values[patch_cells]
    else:
        raise ValueError(f"Field {field} has {len(values)} values, expected {reader.mesh.n_cells} cell values")
    pl = pv.Plotter(off_screen=True, window_size=(1500, 950))
    pl.set_background("white")
    pl.add_mesh(surface, scalars=field, cmap=cmap, smooth_shading=True,
                scalar_bar_args={"title": title, "vertical": True})
    pl.add_axes(line_width=2)
    pl.view_isometric()
    pl.camera.zoom(1.2)
    pl.screenshot(str(output))
    pl.close()
    return finite_stats(arr)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("case", type=Path)
    parser.add_argument("--time", default=None)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()
    case = args.case.resolve()
    out = (args.out or case / "postProcessing" / "foampilot_pyvista").resolve()
    out.mkdir(parents=True, exist_ok=True)
    reader = OpenFOAMDirectReader(case)
    time = args.time or reader.get_latest_time()
    if time in {"0", ""}:
        raise RuntimeError(f"No computed result time available for {case}; selected time={time!r}")

    mesh = reader.to_pyvista(fields=["T", "U", "p_rgh"], time_step=time)
    if "U" in mesh.cell_data:
        mesh["U_mag"] = np.linalg.norm(mesh.cell_data["U"], axis=1)
    fields = [name for name in ("T", "U_mag", "p_rgh") if name in mesh.cell_data]
    stats: dict[str, object] = {
        "case": str(case),
        "time": str(time),
        "n_cells": int(mesh.n_cells),
        "n_points": int(mesh.n_points),
        "fields": {},
        "patches": {},
    }
    for field in fields:
        stats["fields"][field] = finite_stats(mesh.cell_data[field])
        title = {"T": "T [K]", "U_mag": "|U| [m/s]", "p_rgh": "p_rgh [Pa]"}[field]
        cmap = {"T": "inferno", "U_mag": "viridis", "p_rgh": "coolwarm"}[field]
        render_field(mesh, field, out / f"{field}_{time}.png", title, cmap)

    if "T" in fields and "human" in reader.boundary_patches:
        stats["patches"]["human_T"] = render_patch(
            reader, "human", "T", time, out / f"human_T_{time}.png", "Human surface T [K]", "inferno"
        )
    if "U_mag" in fields and "human" in reader.boundary_patches:
        # U_mag is derived from the full volume field; attach it to the patch explicitly.
        patch_cells = reader.get_patch_cells("human")
        surface = reader.mesh.extract_cells(patch_cells).extract_surface().copy()
        surface.cell_data["U_mag"] = surface_cell_values(mesh, surface, mesh.cell_data["U_mag"])
        import pyvista as pv
        pl = pv.Plotter(off_screen=True, window_size=(1500, 950))
        pl.set_background("white")
        pl.add_mesh(surface, scalars="U_mag", cmap="viridis", smooth_shading=True,
                    scalar_bar_args={"title": "Human surface |U| [m/s]", "vertical": True})
        pl.add_axes(line_width=2)
        pl.view_isometric(); pl.camera.zoom(1.2)
        pl.screenshot(str(out / f"human_U_mag_{time}.png")); pl.close()
        stats["patches"]["human_U_mag"] = finite_stats(mesh.cell_data["U_mag"][patch_cells])

    (out / "statistics.json").write_text(json.dumps(stats, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
