"""Tobias Holzmann Rotating Rotor NCC tutorial, FoamPilot runner."""
from pathlib import Path
import shutil
from foampilot.solver import Solver
from foampilot.utilities import OpenFOAMDictAddFile
from templates import FILES

ROOT = Path(__file__).resolve().parent
CASE = ROOT / "case"

def write_case() -> None:
    if CASE.exists():
        shutil.rmtree(CASE)
    writer = OpenFOAMDictAddFile(object_name="tobias_rotating_rotor_ncc")
    for relative, content in FILES.items():
        path = Path(relative)
        if relative == "system/controlDict":
            # Set values for a short smoke run directly in the dict
            # original run script modifies this with foamDictionary, we do it here.
            import re
            content = re.sub(r"endTime\s+10;", "endTime         0.001;", content)
            content = re.sub(r"deltaT\s+0\.2;", "deltaT          0.0005;", content)
            content = re.sub(r"writeInterval\s+0\.2;", "writeInterval   0.001;", content)
        writer.write_raw(path.name, CASE, content, folder=str(Path(*path.parts[:-1])))
    
    shutil.copytree(ROOT / "cad", CASE / "cad", dirs_exist_ok=True)
    shutil.copytree(ROOT / "triSurface", CASE / "constant" / "triSurface", dirs_exist_ok=True)

def run() -> None:
    write_case()
    solver = Solver(CASE)
    
    # Meshing
    solver.run_command(["ideasUnvToFoam", "cad/backgroundMesh.unv"], "log.ideasUnvToFoam")
    solver.run_command(["snappyHexMesh", "-overwrite"], "log.snappyHexMesh")
    solver.run_command(["createPatch", "-overwrite"], "log.createPatch")
    
    # Clean up 0 directory generated by meshing
    if (CASE / "0").exists():
        shutil.rmtree(CASE / "0")
        
    solver.run_command(["createNonConformalCouples", "-overwrite", "AMI1", "AMI2"], "log.createNonConformalCouples")
    
    # Simulation (option 1 in source script)
    shutil.copytree(CASE / "0.orig", CASE / "0")
    
    # renumberMesh is skipped due to known issues with NCC in OpenFOAM 13
    # solver.run_command(["renumberMesh", "-overwrite"], "log.renumberMesh")
    
    solver.run_command(["foamRun"], "log.foamRun")
    
    print(f"Validated Rotating Rotor NCC workflow: {CASE}")

if __name__ == "__main__":
    run()
