"""Tobias Holzmann Catalyst Heat-Up tutorial, FoamPilot runner."""
from pathlib import Path
import shutil
from foampilot.solver import Solver
from foampilot.utilities import OpenFOAMDictAddFile
from templates import FILES

ROOT = Path(__file__).resolve().parent
CASE = ROOT / "case"

def write_case() -> None:
    if CASE.exists():
        shutil.rmtree(CASE)
    writer = OpenFOAMDictAddFile(object_name="tobias_catalyst_heat_up")
    for relative, content in FILES.items():
        path = Path(relative)
        if relative == "system/controlDict":
            # Reduce end time for a smoke run
            import re
            content = re.sub(r"endTime\s+5;", "endTime         1e-5;", content)
            content = re.sub(r"deltaT\s+1e-6;", "deltaT          1e-5;", content)
            content = re.sub(r"writeInterval\s+0\.01;", "writeInterval   1e-5;", content)
        if relative == "system/snappyHexMeshDict":
            # Reduce refinement for smoke run
            content = content.replace("level (2 2);", "level (0 0);")
            content = content.replace("level (3 3);", "level (1 1);")
            content = content.replace("level (4 4);", "level (1 1);")
        if relative in {"system/fvSolution", "system/fluid/fvSolution"}:
            # One outer correction is enough to validate the multi-region workflow
            import re
            content = re.sub(r"nOuterCorrectors\s+20;", "nOuterCorrectors    1;", content)
            content = re.sub(r"nCorrectors\s+2;", "nCorrectors         1;", content)
        writer.write_raw(path.name, CASE, content, folder=str(Path(*path.parts[:-1])))
    
    shutil.copytree(ROOT / "cad", CASE / "cad", dirs_exist_ok=True)
    shutil.copytree(ROOT / "triSurface", CASE / "constant" / "triSurface", dirs_exist_ok=True)

def run() -> None:
    write_case()
    solver = Solver(CASE)
    
    # Meshing
    solver.run_command(["ideasUnvToFoam", "cad/backgroundMesh.unv"], "log.ideasUnvToFoam")
    solver.run_command(["snappyHexMesh", "-overwrite"], "log.snappyHexMesh")
    solver.run_command(["splitMeshRegions", "-cellZones"], "log.splitMeshRegions")
    
    # OpenFOAM 13 writes splitMeshRegions directly to constant/<region>/polyMesh
    # We just need to move the original mesh (which is now the fluid region)
    (CASE / "constant" / "fluid").mkdir(parents=True, exist_ok=True)
    
    # In OF13, splitMeshRegions might overwrite constant/polyMesh or put the fluid in region0/region1 etc.
    # Let's check what it actually did. If SCR1/SCR2 are in constant/, we just need to move constant/polyMesh to fluid/polyMesh
    if (CASE / "constant" / "polyMesh").exists() and not (CASE / "constant" / "fluid" / "polyMesh").exists():
        shutil.move(CASE / "constant" / "polyMesh", CASE / "constant" / "fluid" / "polyMesh")
    
    # Clean up split meshes
    if (CASE / "1e-06").exists():
        shutil.rmtree(CASE / "1e-06")
    for d in CASE.glob("constant/cellToRegion*"):
        if d.is_dir():
            shutil.rmtree(d)
        else:
            d.unlink()
            
    # Create patches for regions
    solver.run_command(["createPatch", "-region", "SCR1", "-overwrite"], "log.createPatch.SCR1")
    solver.run_command(["createPatch", "-region", "SCR2", "-overwrite"], "log.createPatch.SCR2")
    
    # Clean up 0 directory generated by meshing
    if (CASE / "0").exists():
        shutil.rmtree(CASE / "0")
    shutil.copytree(CASE / "0.orig", CASE / "0")
    
    # We skip parallel decomposition and renumbering for the smoke run to simplify the workflow
    # solver.run_command(["decomposePar", "-allRegions"], "log.decomposePar")
    
    solver.run_command(["foamMultiRun"], "log.foamMultiRun")
    
    print(f"Validated Catalyst Heat-Up workflow: {CASE}")

if __name__ == "__main__":
    run()
