#!/bin/sh
cd "${0%/*}" || exit 1
rm -rf constant/polyMesh 1 2 3 4 5 6 7 8 9 10 processor* log.* comms/data.in comms/data.out comms/OpenFOAM.lock comms/patchPoints comms/patchFaces zone_mapping_openfoam.csv
