#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/air/polyMesh
rm -rf constant/leeward/polyMesh
rm -rf constant/street/polyMesh
rm -rf constant/windward/polyMesh

rm -f constant/air/F*
rm -f constant/air/*.gz
rm -f constant/air/constructMap*
rm -f constant/air/finalAgglom*
rm -f constant/air/globalFaceFaces*
rm -f constant/air/subMap*
rm -f constant/air/skyViewCoeff*
rm -f constant/air/sunViewCoeff*
rm -f constant/air/sunskyMap*
rm -f constant/air/sunVisibleOrNot*

rm -f 0/air/viewFactorField*

# ----------------------------------------------------------------- end-of-file
