#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

NPROCS=$(foamDictionary -entry numberOfSubdomains -value system/decomposeParDict)

blockMesh -region air
createPatch -region air -overwrite

echo "Decomposing air region"
decomposePar -region air

echo "Running solver"
mpirun -np $NPROCS urbanMicroclimateFoam -parallel

echo "Reconstructing latest time"
reconstructPar -region air

# ---- Serial alternative ----
# urbanMicroclimateFoam

# ----------------------------------------------------------------- end-of-file
