from foampilot.cht.solver import ChtSolver
from foampilot.cht.regions import FluidRegion, SolidRegion
from foampilot.cht.interfaces import CoupledInterface
from foampilot.cht.boundary_conditions import (
    CoupledTemperatureBC,
    ExternalTemperatureBC,
    HeatFluxBC,
    FixedTemperatureBC,
    InletOutletTemperatureBC,
    SymmetryBC,
    TotalTemperatureBC,
    RadiationCoupledTemperatureBC,
    get_coupled_temperature_bc,
    get_external_temperature_bc,
    get_fixed_temperature_bc,
    get_heat_flux_bc,
    get_inlet_outlet_bc,
    get_symmetry_bc,
    get_total_temperature_bc,
    get_radiation_coupled_temperature_bc,
)
from foampilot.cht.postprocess import (
    calc_region_heat_flux,
    calc_interface_heat_flux,
    calc_nusselt_number,
    calc_thermal_boundary_layer_thickness,
    calc_heat_transfer_coefficient,
    calc_total_heat_balance,
    calc_temperature_contour,
    calc_thermal_resistance,
)
from foampilot.postprocess.openfoam_direct import (
    OpenFOAMDirectReader,
    CHTDirectReader,
    read_openfoam,
    read_cht_openfoam,
)

__all__ = [
    "ChtSolver",
    "FluidRegion",
    "SolidRegion",
    "CoupledInterface",
    "CoupledTemperatureBC",
    "ExternalTemperatureBC",
    "HeatFluxBC",
    "FixedTemperatureBC",
    "InletOutletTemperatureBC",
    "SymmetryBC",
    "TotalTemperatureBC",
    "RadiationCoupledTemperatureBC",
    "get_coupled_temperature_bc",
    "get_external_temperature_bc",
    "get_fixed_temperature_bc",
    "get_heat_flux_bc",
    "get_inlet_outlet_bc",
    "get_symmetry_bc",
    "get_total_temperature_bc",
    "get_radiation_coupled_temperature_bc",
    "calc_region_heat_flux",
    "calc_interface_heat_flux",
    "calc_nusselt_number",
    "calc_thermal_boundary_layer_thickness",
    "calc_heat_transfer_coefficient",
    "calc_total_heat_balance",
    "calc_temperature_contour",
    "calc_thermal_resistance",
    "OpenFOAMDirectReader",
    "CHTDirectReader",
    "read_openfoam",
    "read_cht_openfoam",
]
