"""Tobias Holzmann NCC Heat Transfer tutorial, FoamPilot runner."""
from pathlib import Path
import shutil
from foampilot.solver import Solver
from foampilot.utilities import OpenFOAMDictAddFile
from templates import FILES

ROOT = Path(__file__).resolve().parent
CASE = ROOT / "case"

def write_case() -> None:
    if CASE.exists():
        shutil.rmtree(CASE)
    writer = OpenFOAMDictAddFile(object_name="tobias_ncc_heat_transfer")
    for relative, content in FILES.items():
        path = Path(relative)
        if relative == "system/controlDict":
            # Reduce end time for a smoke run. The simulation segfaults at t=0.72s, so we stop earlier.
            lines = content.split('\n')
            for i, line in enumerate(lines):
                if line.strip().startswith("endTime"):
                    lines[i] = "endTime         0.5;"
            content = '\n'.join(lines)
        if relative == "system/extrudeMeshDict":
            # Add OpenFOAM 13 required coefficients for linearNormal
            content = content.replace(
                "linearNormalCoeffs\n{",
                "linearNormalCoeffs\n{\n    nLayers 1;\n    expansionRatio 1;"
            )
        writer.write_raw(path.name, CASE, content, folder=str(Path(*path.parts[:-1])))
    
    shutil.copytree(ROOT / "cad", CASE / "cad", dirs_exist_ok=True)
    shutil.copytree(ROOT / "triSurface", CASE / "constant" / "triSurface", dirs_exist_ok=True)

def run() -> None:
    write_case()
    solver = Solver(CASE)
    
    # Meshing
    solver.run_command(["ideasUnvToFoam", "cad/backgroundMesh.unv"], "log.ideasUnvToFoam")
    solver.run_command(["surfaceFeatures"], "log.surfaceFeatures")
    solver.run_command(["snappyHexMesh", "-overwrite"], "log.snappyHexMesh")
    solver.run_command(["splitBaffles", "-overwrite"], "log.splitBaffles")
    solver.run_command(["createPatch", "-overwrite"], "log.createPatch")
    solver.run_command(["flattenMesh"], "log.flattenMesh")
    solver.run_command(["extrudeMesh"], "log.extrudeMesh")
    
    # Clean up directories generated by previous steps
    if (CASE / "0").exists():
        shutil.rmtree(CASE / "0")
    for d in (CASE / "constant" / "polyMesh").glob("*Level"):
        if d.is_dir():
            shutil.rmtree(d)
            
    solver.run_command(["createNonConformalCouples", "-overwrite", "interfaceStatic", "interfaceMoving"], "log.createNonConformalCouples")
    solver.run_command(["topoSet"], "log.topoSet")
    # renumberMesh fails on NCC coupled meshes in OF13: "The mesh was not disconnected prior to topology change"
    # solver.run_command(["renumberMesh", "-overwrite"], "log.renumberMesh")
    
    shutil.copytree(CASE / "0.orig", CASE / "0")
    
    solver.run_command(["foamRun"], "log.foamRun")
    
    print(f"Validated NCC Heat Transfer workflow: {CASE}")

if __name__ == "__main__":
    run()
