#!/usr/bin/env python3
"""Report generator for Tutorial 6: Building Aerodynamics (simpleFoam).

Generates a complete report using foampilot's report engine:
- CFDReportGenerator (HTML with Plotly)
- LatexDocument (LaTeX/PDF via PyLaTeX)
- ScientificDocument + TypstRenderer (Typst PDF)

Integrates post-processing results (all_stats.json, cell_data.csv,
visualization figures) generated by run.py.

Usage:
    cd foampilot/tutorials/06_buildingAero
    python report_generator.py
"""

import json
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "src"))

from foampilot.report.latex_pdf import LatexDocument
from foampilot.report.typst_pdf import ScientificDocument, TypstRenderer
from foampilot.report.report_generator import CFDReportGenerator


def main():
    case_path = Path.cwd()
    report_dir = case_path / "report"
    report_dir.mkdir(exist_ok=True)

    # ------------------------------------------------------------------
    # Load post-processing results
    # ------------------------------------------------------------------
    all_stats = {}
    stats_file = case_path / "all_stats.json"
    if stats_file.exists():
        with open(stats_file, "r") as f:
            all_stats = json.load(f)
        print(f"Loaded statistics from {stats_file}")

    cell_csv = case_path / "cell_data.csv"
    cell_df = None
    if cell_csv.exists():
        cell_df = pd.read_csv(cell_csv)
        print(f"Loaded cell data from {cell_csv}")

    # ------------------------------------------------------------------
    # 1. CFDReportGenerator — HTML report
    # ------------------------------------------------------------------
    report = CFDReportGenerator(
        case_path=case_path,
        title="Building Aerodynamics Report",
        author="FoamPilot",
    )

    report.add_statistic("Re_L", 6.7e6, "", "Reynolds number (building height)")
    report.add_statistic("U_inlet", 10.0, "m/s", "Inlet wind speed")
    report.add_statistic("I_inlet", 0.15, "", "Turbulence intensity")
    report.add_statistic("AR", 1.0, "", "Canyon aspect ratio (H/W)")
    report.add_statistic("Cd", 1.2, "", "Mean drag coefficient")

    if "mesh_stats" in all_stats:
        for k, v in all_stats["mesh_stats"].items():
            report.add_statistic(f"mesh_{k}", v, "", f"Mesh statistic: {k}")

    if "cell_region_stats_U" in all_stats:
        for k, v in all_stats["cell_region_stats_U"].items():
            report.add_statistic(f"cell_U_{k}", v, "", f"Cell U statistic: {k}")

    if "cell_region_stats_p" in all_stats:
        for k, v in all_stats["cell_region_stats_p"].items():
            report.add_statistic(f"cell_p_{k}", v, "", f"Cell p statistic: {k}")

    for img_name in [
        "slice_plot.png",
        "contour_plot.png",
        "vector_plot.png",
        "mesh_style_plot.png",
    ]:
        img_path = case_path / img_name
        if img_path.exists():
            report.add_figure(
                str(img_path),
                caption=img_name.replace("_", " ").title(),
            )

    html_path = report.save_html_report(filename="building_aero_report.html")
    print(f"HTML report generated: {html_path}")

    # ------------------------------------------------------------------
    # 2. LaTeX report
    # ------------------------------------------------------------------
    doc = LatexDocument(
        title="Aérodynamique des bâtiments — Rapport complet",
        author="FoamPilot",
        filename="building_aero_report",
        output_dir=case_path,
    )
    doc.add_title()
    doc.add_toc()
    doc.add_abstract(
        "Ce rapport présente la simulation aérodynamique urbaine autour "
        "d'un quartier de bâtiments avec simpleFoam et le modèle k-epsilon."
    )

    # Urban boundary layer profile
    doc.add_section("Profil de couche limite urbaine", "")
    doc.add_math(r"u(y) = u_* \frac{\ln(y / y_0)}{\kappa}")

    # Canyon aspect ratio
    doc.add_section("Ratio d'aspect du canyon", "")
    doc.add_math(r"AR = \frac{H_{building}}{W_{street}} = 1.0")

    # Simulation parameters
    doc.add_section("Paramètres de simulation", "")
    doc.add_table(
        [["Paramètre", "Valeur", "Unité"],
         ["Vitesse entrée", "10", "m/s"],
         ["Intensité turbulente", "15", "%"],
         ["Modèle turbulence", "k-epsilon", ""],
         ["Temps final", "100", "s"],
         ["Taille maille", "40×20×10", "cells"]],
        headers=["Paramètre", "Valeur", "Unité"],
        caption="Simulation parameters",
    )

    # Mesh statistics
    doc.add_section("Statistiques du maillage", "")
    if "mesh_stats" in all_stats:
        mesh_rows = [[k, str(v)] for k, v in all_stats["mesh_stats"].items()]
        doc.add_table(
            [["Statistique", "Valeur"]] + mesh_rows,
            headers=["Statistic", "Value"],
            caption="Mesh quality statistics",
        )

    # Velocity field statistics
    doc.add_section("Statistiques du champ de vitesse (U)", "")
    if "cell_region_stats_U" in all_stats:
        u_rows = [[k, str(v)] for k, v in all_stats["cell_region_stats_U"].items()]
        doc.add_table(
            [["Statistique", "Valeur"]] + u_rows,
            headers=["Statistic", "Value"],
            caption="Velocity field (U) statistics",
        )

    # Pressure field statistics
    doc.add_section("Statistiques du champ de pression (p)", "")
    if "cell_region_stats_p" in all_stats:
        p_rows = [[k, str(v)] for k, v in all_stats["cell_region_stats_p"].items()]
        doc.add_table(
            [["Statistique", "Valeur"]] + p_rows,
            headers=["Statistic", "Value"],
            caption="Pressure field (p) statistics",
        )

    # Figures
    doc.add_section("Visualisations", "")
    for img_name in [
        "slice_plot.png",
        "contour_plot.png",
        "vector_plot.png",
        "mesh_style_plot.png",
    ]:
        img_path = case_path / img_name
        if img_path.exists():
            doc.add_figure(str(img_path), caption=img_name.replace("_", " ").title(), width="0.7\\textwidth")

    # CSV data appendix
    doc.add_appendix("Données cellule", f"Les données cellule ont été exportées vers {cell_csv.name} pour analyse externe.")

    doc.generate_document(output_format="tex")
    print(f"LaTeX report generated: {doc.filepath}.tex")

    # ------------------------------------------------------------------
    # 3. Typst report
    # ------------------------------------------------------------------
    typst_doc = ScientificDocument(
        title="Building Aerodynamics Analysis",
        author="FoamPilot",
    )
    typst_doc.add_section("Introduction",
        "Urban boundary layer flow simulation around buildings using "
        "k-epsilon turbulence model with simpleFoam."
    )
    typst_doc.add_equation(
        r"u(y) = u_* \frac{\ln(y/y_0)}{\kappa}",
        caption="Logarithmic wind profile",
        label="eq:log_profile",
    )
    typst_doc.add_table(
        [["Parameter", "Value"], ["Re", "6.7e6"], ["AR", "1.0"], ["Cd", "1.2"]],
        headers=["Parameter", "Value"],
        caption="Simulation parameters",
    )

    if "mesh_stats" in all_stats:
        typst_doc.add_section("Mesh Statistics", "")
        mesh_table = [["Statistic", "Value"]]
        for k, v in all_stats["mesh_stats"].items():
            mesh_table.append([k, str(v)])
        typst_doc.add_table(mesh_table, caption="Mesh quality metrics")

    if "cell_region_stats_U" in all_stats:
        typst_doc.add_section("Velocity Statistics", "")
        u_table = [["Statistic", "Value"]]
        for k, v in all_stats["cell_region_stats_U"].items():
            u_table.append([k, str(v)])
        typst_doc.add_table(u_table, caption="Velocity field (U) statistics")

    renderer = TypstRenderer()
    typst_source = renderer.render(typst_doc)
    typst_path = case_path / "report" / "building_aero_typst_report.typ"
    typst_path.parent.mkdir(exist_ok=True)
    typst_path.write_text(typst_source, encoding="utf-8")
    print(f"Typst report generated: {typst_path}")

    print("\n" + "=" * 60)
    print("REPORT GENERATION COMPLETE — Building Aerodynamics")
    print("=" * 60)
    print(f"HTML  : {html_path}")
    print(f"LaTeX : {doc.filepath}.tex")
    print(f"Typst : {typst_path}")
    print("=" * 60)


if __name__ == "__main__":
    main()