from pathlib import Path
import json, vtk, numpy as np
ROOT=Path(__file__).resolve().parents[2] / 'case_complex'; report=json.loads((ROOT/'build123d_branch_parallel'/'parallel_benchmark_report.json').read_text()); manifest=json.loads((ROOT/'openfoam_surface_patches'/'patch_manifest.json').read_text()); stl_report={}
for name,info in manifest['patches'].items():
 path=Path(info['stl']); r=vtk.vtkSTLReader(); r.SetFileName(str(path)); r.Update(); p=r.GetOutput(); fe=vtk.vtkFeatureEdges(); fe.SetInputData(p); fe.BoundaryEdgesOn(); fe.FeatureEdgesOff(); fe.NonManifoldEdgesOn(); fe.Update(); stl_report[name]={'exists':path.exists(),'file_size':path.stat().st_size if path.exists() else 0,'points':p.GetNumberOfPoints(),'cells':p.GetNumberOfCells(),'boundary_edges':fe.GetOutput().GetNumberOfLines(),'bounds':list(p.GetBounds()) if p.GetNumberOfPoints() else None}
out={'build123d':report,'surface_patches':{'manifest':manifest,'stl_validation':stl_report},'openfoam_case':'openfoam_surface_patches/case_motorbike_style','limitations':['blockMesh, surfaceFeatureExtract, snappyHexMesh and checkMesh were not installed in the sandbox','STL patch classification is geometric and must be checked visually in ParaView/OpenFOAM','the Build123d branch solids are individually valid but still require global intersection and union validation']}
(ROOT/'BUILD123D_OPENFOAM_COMPLEX_REPORT.json').write_text(json.dumps(out,indent=2,default=lambda x:x.item() if hasattr(x,'item') else str(x)))
rows=[]
for method in ('smooth','ruled'):
 for r in report['branches']:
  if r['method']==method: rows.append(f"| {r['branch_id']} | {method} | {r['ok']} | {r.get('volume')} | {r.get('faces')} | {r.get('build_time_s')} |")
md='''# Benchmark Build123d et export OpenFOAM — aorte complexe\n\n## Build123d\n\n| Branche | Méthode | OCC valide | Volume signé | Faces | Temps de construction (s) |\n|---:|---|---:|---:|---:|---:|\n'''+"\n".join(rows)+'''\n\nLe loft lisse est rapide et produit 34 faces après projection des profils, mais la branche 5 conserve un volume signé négatif malgré `is_valid=True`; elle doit donc être corrigée par orientation/reversal avant union globale. Le loft réglé produit 3170 faces par branche, aucun volume négatif et demande environ deux fois plus de temps de construction.\n\n## Patches STL\n\n| Patch | Triangles | Points | Arêtes de bord détectées |\n|---|---:|---:|---:|\n'''+"\n".join(f"| {k} | {v['cells']} | {v['points']} | {stl_report[k]['boundary_edges']} |" for k,v in manifest['patches'].items())+'''\n\nLes STL sont placés dans `constant/triSurface` du cas `case_motorbike_style`. Le cas contient un `blockMeshDict` de fond, un `snappyHexMeshDict`, un `surfaceFeatureExtractDict` et un README.\n\n## Limites\n\nLes exécutables OpenFOAM n’étaient pas installés dans l’environnement de test. La validation finale doit donc être exécutée avec `blockMesh`, `surfaceFeatureExtract`, `snappyHexMesh` et `checkMesh`.\n'''
(ROOT/'BUILD123D_OPENFOAM_COMPLEX_REPORT.md').write_text(md)
print({'report_json':str(ROOT/'BUILD123D_OPENFOAM_COMPLEX_REPORT.json'),'report_md':str(ROOT/'BUILD123D_OPENFOAM_COMPLEX_REPORT.md'),'stl_patches':list(stl_report)})
